version: "2"
services:
  app:
    container_name: app
    image: kaholoio/kaholo-server:latest
    restart: always
    build: .
    environment:
      - MONGO_HOST=mongo
    ports:
      - "8080:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.6
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
